Dominik polacek frontend
TDZ-production/todoz pull request #8
Opened 2023-12-12 16:18 UTC by Dominik-Polacek

added html / css / controller to our code

2023-12-12 16:37 UTC, yenik approved these changes
well merged

2023-12-12 16:37 UTC, Davias97 approved these changes
frontend best end

2023-12-12 16:39 UTC, dovantuan97 approved these changes
goood stuff

2023-12-12 16:46 UTC, ales requested changes
prosim, odstrante ty .DS_Store soubory a pridejte je do gitignore 🥺 cau ja jsem ales

2023-12-13 10:13 UTC, Simebe30 approved these changes

2023-12-13 10:15 UTC, Simebe30 approved these changes

2023-12-13 10:17 UTC, ales approved these changes

2023-12-13 10:18 UTC, merged